//  ██████╗ ██████╗ ███╗   ███╗
// ██╔════╝██╔═══██╗████╗ ████║
// ██║     ██║   ██║██╔████╔██║
// ██║     ██║   ██║██║╚██╔╝██║
// ╚██████╗╚██████╔╝██║ ╚═╝ ██║
//  ╚═════╝ ╚═════╝ ╚═╝     ╚═╝

export const COMStructure: Type[] = [
    [ 8, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 2, 'signed' ],
    [ 2, 'signed' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ]
];

export const COMObj = {
    timestamp: '',
    fwVersion: '',
    activeCOM: '',
    digipeaterMode: '',
    numberOfReboots: '',
    outputReflectedPower: '',
    outputForwardPower: '',
    outputReflectedPowerCW: '',
    outputForwardPowerCW: '',
    rssi: '',
    rssiNoise: '',
    mcuTemperature: '',
    paTemperature: '',
    cwBeaconSent: '',
    packetsSent: '',
    correctPacketsReceived: '',
    brokenPacketReceived: '',
    comProtocolError: '',
    gsProtocolError: '',
    txDisableStatus: '',
    orbitTime: '',
    timeslotStart: '',
    timeslotEnd: '',
}

//  █████╗ ██████╗  ██████╗███████╗
// ██╔══██╗██╔══██╗██╔════╝██╔════╝
// ███████║██║  ██║██║     ███████╗
// ██╔══██║██║  ██║██║     ╚════██║
// ██║  ██║██████╔╝╚██████╗███████║
// ╚═╝  ╚═╝╚═════╝  ╚═════╝╚══════╝

export const ADCSStructure: Type[] = [
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 2, 'unsigned' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 2, 'unsigned' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 2, 'unsigned' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 2, 'unsigned' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 2, 'unsigned' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 2, 'unsigned' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ]
];

export const ADCSObj = {
    'adcsMode': '',
    'bdK': '',
    'maxPwmCoilX': '',
    'maxPwmCoilY': '',
    'maxPwmCoilZ': '',
    'sunXPlusX': '',
    'sunXPlusY': '',
    'sunXPlusIrrad': '',
    'sunXMinusX': '',
    'sunXMinusY': '',
    'sunXMinusIrrad': '',
    'sunYPlusX': '',
    'sunYPlusY': '',
    'sunYPlusIrrad': '',
    'sunYMinusX': '',
    'sunYMinusY': '',
    'sunYMinusIrrad': '',
    'sunZPlusX': '',
    'sunZPlusY': '',
    'sunZPlusIrrad': '',
    'sunZMinusX': '',
    'sunZMinusY': '',
    'sunZMinusIrrad': '',
    'gyroX': '',
    'gyroY': '',
    'gyroZ': '',
    'gyroTemp': '',
    'mag1X': '',
    'mag1Y': '',
    'mag1Z': '',
    'mag1Temp': '',
    'mag2X': '',
    'mag2Y': '',
    'mag2Z': '',
    'mag2Temp': '',
    'accelX': '',
    'accelY': '',
    'accelZ': '',
    'accelTemp': '',
    'earthXPlus': '',
    'earthXMinus': '',
    'earthYPlus': '',
    'earthYMinus': '',
}

//  ██████╗██████╗ ██╗  ██╗███████╗
// ██╔════╝██╔══██╗██║  ██║██╔════╝
// ██║     ██║  ██║███████║███████╗
// ██║     ██║  ██║██╔══██║╚════██║
// ╚██████╗██████╔╝██║  ██║███████║
//  ╚═════╝╚═════╝ ╚═╝  ╚═╝╚══════╝

export const CDHSStructure: Type[] = [
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 8, 'unsigned' ],
    [ 8, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 8, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 2, 'unsigned' ],
    [ 2, 'unsigned' ]
];

export const CDHSObj = {
  'antFired': '',
  'antAttempts': '',
  'antFiredInv': '',
  'numReboots': '',
  'time': '',
  'bootLog': '',
  'verProt': '',
  'swVersion': '',
  'swRelease': '',
  'drvVersion': '',
  'drvRelease': '',
  'activeCpu': '',
  'comRecv': '',
  'comSend': '',
  'comFwd': '',
  'comRecvErr': '',
  'comSendErr': '',
  'comFwdErr': '',
  'rxFwdCam': '',
  'rxFwdPwr': '',
  'rxFwdExp': '',
  'rxFwdCamErr': '',
  'rxFwdPwrErr': '',
  'rxFwdExpErr': '',
  'unused5': '',
  'unused6': '',
  'unused7': '',
  'unused8': '',
  'unused9': '',
  'unused10': '',
  'unused11': '',
  'unused12': '',
  'stackUsageMax': '',
  'cpuUsageAvg': '',
  'cpuUsageMax': '',
  'cpuTemp': '',
  'taskNumActiv[14]': '',
  'calibMode': '',
  'calibStop': '',
  'calibDlay': '',
  'calibRemainSmpls': '',
  'osBootLog': '',
  'osBootLog2': '',
  'taskCheckLog': '',
  'delayWrtB7': '',
  'radOn': '',
  'radRamPattern1': '',
  'radRamPattern2': '',
  'radRamPattern3': '',
  'radRamPattern4': '',
  'radRamPattern5': '',
  'radRamErr': '',
  'radFrmPattern1': '',
  'radFrmPattern2': '',
  'radFrmPattern3': '',
  'radFrmPattern4': '',
  'radFrmPattern5': '',
  'radFrmErr': '',
  'flashBootromCrcWrong': '',
  'flashOperCrcWrong': '',
};


// ██████╗ ██╗    ██╗██████╗
// ██╔══██╗██║    ██║██╔══██╗
// ██████╔╝██║ █╗ ██║██████╔╝
// ██╔═══╝ ██║███╗██║██╔══██╗
// ██║     ╚███╔███╔╝██║  ██║
// ╚═╝      ╚══╝╚══╝ ╚═╝  ╚═╝

export const PWRStructure: Type[] = [
    [ 8, 'unsigned' ],
    [ 8, 'unsigned' ],
    [ 8, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'signed' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'signed' ],
    [ 8, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
    [ 4, 'unsigned' ],
];

export const PWRObj = {
    'timestamp': '',
    'fullUptime': '',
    'uptime': '',
    'activeUP': '',
    'fwVer': '',
    'reboots': '',
    'countCOMErrors': '',
    'countPSUErrors': '',
    'iSolarYp': '',
    'iSolarXp': '',
    'iSolarYm': '',
    'iSolarXm': '',
    'iSolarZp': '',
    'iSolarZm': '',
    'tSolarYp': '',
    'tSolarXp': '',
    'tSolarYm': '',
    'tSolarXm': '',
    'tSolarZp': '',
    'tSolarZm': '',
    'uBatA': '',
    'uBatB': '',
    'tBat': '',
    'cBatA': '',
    'cBatB': '',
    'capacity': '',
    'iBatA': '',
    'iBatB': '',
    'iBatAmin': '',
    'iBatBmin': '',
    'iBatAmax': '',
    'iBatBmax': '',
    'iBatAavg': '',
    'iBatBavg': '',
    'iCDHSmin': '',
    'iCDHSmax': '',
    'iCDHSavg': '',
    'iCDHSactual': '',
    'iCOMmin': '',
    'iCOMmax': '',
    'iCOMavg': '',
    'iCOMactual': '',
    'iCAMmin': '',
    'iCAMmax': '',
    'iCAMavg': '',
    'iCAMactual': '',
    'iEXPmin': '',
    'iEXPmax': '',
    'iEXPavg': '',
    'iEXPactual': '',
    'iADCSmin': '',
    'iADCSmax': '',
    'iADCSavg': '',
    'iADCSactual': '',
    'uSYSmin': '',
    'uSYSmax': '',
    'uSYSactual': '',
    'iOverBit': '',
    'connectBit': '',
    'tsTemp': '',
    'countCOMpacket': '',
    'PSUError': '',
    'PSULastError': '',
    'COMError': '',
    'COMLastError': '',
    'endofdata': '',
}
